/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.harper.asteroids;

import org.junit.Ignore;
import org.junit.Test;

import java.net.MalformedURLException;

import static org.junit.Assert.*;

public class AppTest {
    @Ignore
    @Test public void testAppHasAGreeting() throws MalformedURLException {
        App classUnderTest = new App();

    }
}
